build:
  dependencies:
    before:
      - npm install node-pre-gyp
  environment:
    variables:
      JWT_SECRET: 'AlongSecretThatIsEnoughForTesting'
filter:
  excluded_paths:
    - "node_modules/"
checks:
  javascript: true


