
node_js:
    - "node"
    - "10"
    - "8"
    - "6"

sudo: false

git:
    submodules: false

env:
    - JWT_SECRET="AlongSecretThatIsEnoughForTesting"

before_script:
    - npm install

script:
    - npm test 